openapi: 3.0.4
info:
  title: By Trail API
  description: |-
    This is 'By Trail', a SaaS to plan and monitor trekking based 
    on the OpenAPI 3.0 specification.

    Useful links:
    - [The By Trail repository](https://github.com/g-mainardi/by-trail)
    - [The By Trail client application](https://by-trail-client.onrender.com)
    - [The By Trail server application](https://by-trail-server.onrender.com/api)

    Note: authenticated users are identified via a JWT token passed in the
    `Authorization` header as a Bearer token and their requests are handled first by an authentication middleware.
  version: 1.0.2
servers:
  - url: http://localhost:3000/api
    description: Local Docker Development Server
  - url: https://by-trail-server.onrender.com/api
    description: Production Server

security:
  - bearerAuth: []

tags:
  - name: Authentication
    description: User authentication and authorization
  - name: Notifications
    description: User notifications management
  - name: Admin
    description: Administrative operations and management
  - name: Users
    description: User profile, settings, and preferences
  - name: Favorites
    description: Management of user favorite bivouacs and routes
  - name: Bivouacs
    description: Management of shelters and bivouacs
  - name: Routes
    description: Management of hiking routes
  - name: Intentions
    description: Bivouac booking management
  - name: Proposals
    description: Route or Bivouac proposals by users

paths:
  # Authentication
  /auth/login:
    $ref: './paths/authentication.yaml#/login'
  /auth/signup:
    $ref: './paths/authentication.yaml#/signup'
  /auth/delete:
    $ref: './paths/authentication.yaml#/delete'

  # Users
  /users/profile:
    $ref: './paths/users.yaml#/profile'
  /users/favorites/bivouacs:
    $ref: './paths/users.yaml#/favorites/bivouacs'
  /users/favorites/routes:
    $ref: './paths/users.yaml#/favorites/routes'
  /users/intentions:
    $ref: './paths/users.yaml#/intentions'

  # Bivacchi
  /bivouacs:
    $ref: './paths/bivouacs.yaml#/list'
  /bivouacs/{id}:
    $ref: './paths/bivouacs.yaml#/getById'
  /bivouacs/intentions/{id}:
    $ref: './paths/bivouacs.yaml#/getIntentions'

  # Routes
  /routes:
    $ref: './paths/routes.yaml#/list'
  /routes/{id}:
    $ref: './paths/routes.yaml#/getById'

  # Proposals
  /proposals:
    $ref: './paths/proposals.yaml#/sendProposal'

  # Notifications
  /notifications:
    $ref: './paths/notifications.yaml#/list'
  /notifications/{id}:
    $ref: './paths/notifications.yaml#/deleteById'
  /notifications/{id}/read:
    $ref: './paths/notifications.yaml#/markReadById'
  /notifications/read-all:
    $ref: './paths/notifications.yaml#/markAllRead'
  /notifications/test-realtime-reservation:
    $ref: './paths/notifications.yaml#/testRealtimeReservation'

  # Admin
  /admin/users:
    $ref: './paths/admin.yaml#/listUsers'
  /admin/users/{id}:
    $ref: './paths/admin.yaml#/deleteUserById'
  /admin/users/{id}/status:
    $ref: './paths/admin.yaml#/updateUserStatus'
  /admin/bivouacs/{id}:
    $ref: './paths/admin.yaml#/manageBivouacById'
  /admin/routes/{id}:
    $ref: './paths/admin.yaml#/manageRouteById'
  /admin/proposals:
    $ref: './paths/admin.yaml#/listProposals'
  /admin/proposals/{id}:
    $ref: './paths/admin.yaml#/deleteProposalById'

components:
  securitySchemes:
    bearerAuth:
      $ref: './components/security.yaml#/bearerAuth'
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    Proposal:
      $ref: './components/schemas/Proposal.yaml'
    Bivouac:
      $ref: './components/schemas/Bivouac.yaml'
    Route:
      $ref: './components/schemas/Route.yaml'
    Reservation:
      $ref: './components/schemas/Reservation.yaml'
    Error:
      $ref: './components/messages.yaml#/Error'
    Success:
      $ref: './components/messages.yaml#/Success'
    CreateReservationRequest:
      $ref: './components/requests.yaml#/CreateReservationRequest'
    RequestWithinBoundingBox:
      $ref: './components/requests.yaml#/RequestWithinBoundingBox'
    LoginRequest:
      $ref: './components/requests.yaml#/LoginRequest'
    SignupRequest:
      $ref: './components/requests.yaml#/SignupRequest'
    UserUpdateRequest:
      $ref: './components/requests.yaml#/UserUpdateRequest'
  parameters:
    $ref: './components/parameters.yaml'
  responses:
    $ref: './components/responses.yaml'
