openapi: 3.0.4
info:
  title: By Trail API
  description: |-
    This is 'By Trail', a SaaS to plan and monitor trekking based 
    on the OpenAPI 3.0 specification.

    Useful links:
    - [The By Trail repository](https://github.com/g-mainardi/by-trail)

    Note: authenticated users are identified via a JWT token passed in the
    `Authorization` header as a Bearer token and their requests are handled first by an authentication middleware.
  version: 1.0.1
servers:
  - url: http://localhost:8080
    description: Local Docker Server

tags:
  - name: Authentication
    description: User authentication and authorization
  - name: Alerts
    description: Management of user alerts and notifications
  - name: Admin
    description: Administrative operations and management
  - name: Users
    description: User profiles, settings, and lists
  - name: Bivacchi
    description: Management of shelters and bivouacs
  - name: Trails
    description: Management of hiking trails
  - name: Reservations
    description: Bivouac booking management
  - name: Proposals
    description: Route or Bivouac proposals by users

paths:
  # Authentication
  /auth/login:
    $ref: './paths/authentication.yaml#/~1login'
  /auth/signup:
    $ref: './paths/authentication.yaml#/~1signup'
  /auth/delete:
    $ref: './paths/authentication.yaml#/~1delete'
  # Users
  /users:
    $ref: './paths/users.yaml#/~1users'
  # Bivacchi

  # Trails

  # Reservations

  # Proposals
  /proposal:
    $ref: './paths/proposal.yaml#/~1proposal'

  # Alerts

  # Admin

components:
  schemas:
    User:
      $ref: './components/schemas/User.yaml'
    Proposal:
      $ref: './components/schemas/Proposal.yaml'
