services:
  # Backend (API)
  server:
    container_name: by-trail-server-prod
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - '3000:3000'
    secrets:
      - db_uri
      - jwt_secret
    environment:
      PORT: ${SERVER_PORT:-3000}
      CLIENT_ORIGIN: http://${CLIENT_HOST:-localhost}:${CLIENT_PORT:-5173}
      MONGO_URI_FILE: /run/secrets/db_uri
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      USE_ATLAS: '${USE_ATLAS:-true}'
      NODE_ENV: production

  # Frontend (Nginx)
  client:
    container_name: by-trail-client-prod
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        VITE_PORT: 5173
        VITE_SERVER_URL: http://localhost:3000
        VITE_SOCKET_URL: http://localhost:3000
    ports:
      - '5173:80' # Map host port 5173 to container port 80 (Nginx)
    secrets:
      - map_api_key

    depends_on:
      - server

secrets:
  db_uri:
    file: ./secrets/mongo_atlas_uri.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  map_api_key:
    file: ./secrets/thunderforest_map_key.txt
