services:
  # 1. Local Database
  mongo:
    image: mongo
    profiles: ['local-db']
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db # persist data, to insert real db path

  # 2. Mongo Express GUI (optional for local DB)
  mongo-express:
    image: mongo-express
    profiles: ['local-db']
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: 'false'
    depends_on:
      - mongo

  # 3. Backend (Node/Express)
  server:
    container_name: by-trail-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
      target: builder # Use the builder stage for dev
    ports:
      - '3000:3000'
    secrets:
      - db_uri
      - jwt_secret
    environment:
      PORT: ${SERVER_PORT:-3000}
      CLIENT_ORIGIN: http://${CLIENT_HOST:-localhost}:${CLIENT_PORT:-5173}
      MONGO_URI_FILE: /run/secrets/db_uri
      MONGO_URI_LOCAL: mongodb://mongo:27017/by_trail
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      # Logic handled inside the app: to use Atlas or local MongoDB
      USE_ATLAS: '${USE_ATLAS:-true}'
      NODE_ENV: development # Force development mode

    # Override the default command to enable hot-reload with nodemon
    command: npm run dev:server

    volumes:
      - ./server:/app/server
      - ./shared:/app/shared # Critical! Allows hot-reload if you change schemas
      - /app/node_modules
      - /app/server/node_modules # Preserve container deps
      - /app/shared/node_modules # Preserve shared deps
      - /app/shared/dist

  # 4. Frontend (Vite/React)
  client:
    container_name: by-trail-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
      target: builder # Use the builder stage for dev
    ports:
      - '5173:5173'
    secrets:
      - map_api_key
    environment:
      VITE_PORT: ${CLIENT_PORT:-5173}
      VITE_SERVER_URL: http://${SERVER_HOST:-localhost}:${SERVER_PORT:-3000}
      VITE_SOCKET_URL: http://${SERVER_HOST:-localhost}:${SERVER_PORT:-3000}
      VITE_MAP_API_KEY_FILE: /run/secrets/map_api_key # We tell Vite where to look for the key file inside the container
      CHOKIDAR_USEPOLLING: 'true' # Tell Vite to use polling (better FS changes detection in Docker)
    command: npm run dev:client --host
    volumes:
      - ./client:/app/client
      - ./shared:/app/shared # Critical! Allows hot-reload if you change schemas
      - /app/node_modules
      - /app/client/node_modules # Preserve container deps
      - /app/shared/node_modules # Preserve shared deps
      - /app/shared/dist

    depends_on:
      - server

secrets:
  db_uri:
    file: ./secrets/mongo_atlas_uri.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  map_api_key:
    file: ./secrets/thunderforest_map_key.txt

volumes:
  mongo-data: # named volume to not lost data on turn off
